### ISSUE TITLE
Implementeer 'Create All' button voor batch export van radar charts

### ISSUE THREAD

**Issue by Fbeunder** [Fbeunder/RadarChart#23]
## Beschrijving
Implementeer een 'Create All' button die het mogelijk maakt om voor alle personen in één keer radar chart afbeeldingen te genereren en op te slaan als GIF bestanden.

## Doel, Nut en Noodzaak
**Doel:** HR-professionals en managers in staat stellen om met één klik voor alle medewerkers feedback visualisaties te exporteren, zodat deze kunnen worden gebruikt in presentaties, rapporten of persoonlijke ontwikkelgesprekken.

**Doelgroep:** HR-professionals, teamleiders en managers die feedback resultaten willen delen met medewerkers of management.

**Nut:**
- Tijdsbesparing: In plaats van elke persoon individueel te selecteren en handmatig screenshots te maken, kunnen alle visualisaties in één keer worden gegenereerd
- Consistentie: Alle afbeeldingen hebben dezelfde opmaak en kwaliteit
- Archivering: Feedback resultaten kunnen eenvoudig worden bewaard voor toekomstige referentie
- Offline gebruik: Gegenereerde afbeeldingen kunnen worden gebruikt in presentaties zonder toegang tot de applicatie

#### 1.1 HTML (templates/index.html)
Voeg een nieuwe sectie toe na de personen selectie:
```html
<!-- Batch Export Sectie -->
<div id="batchExportSection" style="display: none;">
    <div class="batch-export-container">
        <h3>📦 Batch Export</h3>
        <p>Genereer radar charts voor alle personen tegelijk</p>
        <button id="createAllButton" class="create-all-btn">
            <span class="btn-icon">🎯</span>
            Create All
        </button>
        <div id="exportProgress" style="display: none;">
            <div class="progress-bar">
                <div class="progress-fill"></div>
            </div>
            <p class="progress-text">Verwerken: <span id="currentPerson"></span></p>
        </div>
    </div>
</div>
```

#### 1.2 CSS (static/css/style.css)
```css
.batch-export-container {
    background: #f8f9fa;
    border-radius: 8px;
    padding: 20px;
    margin-top: 20px;
    text-align: center;
}

.create-all-btn {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    border: none;
    padding: 12px 30px;
    border-radius: 25px;
    font-size: 16px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s ease;
    display: inline-flex;
    align-items: center;
    gap: 10px;
}

.create-all-btn:hover {
    transform: translateY(-2px);
    box-shadow: 0 5px 15px rgba(102, 126, 234, 0.4);
}

.create-all-btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
}

.btn-icon {
    font-size: 20px;
}

#exportProgress {
    margin-top: 20px;
}

.progress-text {
    margin-top: 10px;
    font-size: 14px;
    color: #666;
}
```

#### 1.3 JavaScript (static/js/main.js)
Voeg de volgende functionaliteit toe:

```javascript
// Voeg toe aan bestaande event listeners
document.getElementById('createAllButton').addEventListener('click', handleCreateAll);

// Toon batch export sectie na succesvolle upload
function showBatchExportSection() {
    const batchExportSection = document.getElementById('batchExportSection');
    batchExportSection.style.display = 'block';
}

// Handler voor Create All button
async function handleCreateAll() {
    const createAllButton = document.getElementById('createAllButton');
    const exportProgress = document.getElementById('exportProgress');
    const currentPersonSpan = document.getElementById('currentPerson');
    const progressFill = document.querySelector('#exportProgress .progress-fill');
    
    // Vraag om export locatie
    const exportPath = await showExportDialog();
    if (!exportPath) return;
    
    createAllButton.disabled = true;
    exportProgress.style.display = 'block';
    
    try {
        // Haal lijst van personen op
        const response = await fetch('/status');
        const data = await response.json();
        const persons = data.available_persons;
        
        // Verwerk elke persoon
        for (let i = 0; i < persons.length; i++) {
            const person = persons[i];
            currentPersonSpan.textContent = person;
            progressFill.style.width = `${((i + 1) / persons.length) * 100}%`;
            
            // Genereer en download GIF voor deze persoon
            await generateAndSaveGIF(person, exportPath);
            
            // Kleine delay om UI te updaten
            await new Promise(resolve => setTimeout(resolve, 100));
        }
        
        showStatus('success', `✅ Alle ${persons.length} radar charts zijn succesvol geëxporteerd naar ${exportPath}`);
        
    } catch (error) {
        console.error('Export error:', error);
        showStatus('error', `❌ Fout bij exporteren: ${error.message}`);
    } finally {
        createAllButton.disabled = false;
        exportProgress.style.display = 'none';
    }
}

// Toon export dialog
async function showExportDialog() {
    // Maak custom dialog
    const dialog = document.createElement('div');
    dialog.className = 'export-dialog-overlay';
    dialog.innerHTML = `
        <div class="export-dialog">
            <h3>📁 Selecteer Export Locatie</h3>
            <p>Standaard locatie: C:\\temp</p>
            <input type="text" id="exportPath" value="C:\\temp" class="export-path-input">
            <p class="export-hint">Tip: Zorg dat de map bestaat en schrijfrechten heeft</p>
            <div class="dialog-buttons">
                <button id="confirmExport" class="btn-primary">Exporteren</button>
                <button id="cancelExport" class="btn-secondary">Annuleren</button>
            </div>
        </div>
    `;
    
    document.body.appendChild(dialog);
    
    return new Promise((resolve) => {
        document.getElementById('confirmExport').onclick = () => {
            const path = document.getElementById('exportPath').value;
            document.body.removeChild(dialog);
            resolve(path);
        };
        
        document.getElementById('cancelExport').onclick = () => {
            document.body.removeChild(dialog);
            resolve(null);
        };
    });
}

// Genereer en sla GIF op voor een persoon
async function generateAndSaveGIF(personName, exportPath) {
    // Haal scores op
    const response = await fetch(`/get_scores/${encodeURIComponent(personName)}`);
    const data = await response.json();
    
    if (!data.success) {
        throw new Error(`Kon scores niet ophalen voor ${personName}`);
    }
    
    // Maak tijdelijke container voor chart
    const tempContainer = document.createElement('div');
    tempContainer.id = 'temp-chart-container';
    tempContainer.style.position = 'absolute';
    tempContainer.style.left = '-9999px';
    tempContainer.style.width = '800px';
    tempContainer.style.height = '800px';
    document.body.appendChild(tempContainer);
    
    // Render chart
    const chart = initializeRadarChart('#temp-chart-container', data.scores, personName, {
        w: 600,
        h: 600,
        margin: { top: 100, right: 100, bottom: 100, left: 100 }
    });
    
    // Wacht tot chart volledig gerenderd is
    await new Promise(resolve => setTimeout(resolve, 500));
    
    // Converteer naar GIF via backend
    const svg = tempContainer.querySelector('svg');
    const svgData = new XMLSerializer().serializeToString(svg);
    
    const gifResponse = await fetch('/export_gif', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            svg_data: svgData,
            person_name: personName,
            export_path: exportPath
        })
    });
    
    if (!gifResponse.ok) {
        throw new Error(`Export mislukt voor ${personName}`);
    }
    
    // Cleanup
    chart.destroy();
    document.body.removeChild(tempContainer);
}
```

#### 2.1 Nieuwe dependencies (requirements.txt)
```
cairosvg==2.7.1
Pillow==10.1.0
```

#### 2.2 Nieuwe route in app.py
```python
from flask import Flask, request, jsonify, send_file
import cairosvg
from PIL import Image
import io
from datetime import datetime
import os

@app.route('/export_gif', methods=['POST'])
def export_gif():
    """Converteer SVG naar GIF en sla op"""
    try:
        data = request.json
        svg_data = data.get('svg_data')
        person_name = data.get('person_name')
        export_path = data.get('export_path', 'C:\\temp')
        
        if not svg_data or not person_name:
            return jsonify({
                'error': 'SVG data en persoon naam zijn verplicht',
                'success': False
            }), 400
        
        # Maak export directory aan als deze niet bestaat
        os.makedirs(export_path, exist_ok=True)
        
        # Genereer bestandsnaam
        date_str = datetime.now().strftime('%Y%m%d')
        filename = f"{date_str}_{person_name.replace(' ', '_')}.gif"
        filepath = os.path.join(export_path, filename)
        
        # Converteer SVG naar PNG eerst (GIF direct wordt niet ondersteund)
        png_data = cairosvg.svg2png(bytestring=svg_data.encode('utf-8'))
        
        # Converteer PNG naar GIF met Pillow
        image = Image.open(io.BytesIO(png_data))
        
        # Converteer RGBA naar RGB met witte achtergrond
        if image.mode == 'RGBA':
            background = Image.new('RGB', image.size, (255, 255, 255))
            background.paste(image, mask=image.split()[3])
            image = background
        
        # Sla op als GIF
        image.save(filepath, 'GIF', optimize=True)
        
        return jsonify({
            'success': True,
            'filename': filename,
            'filepath': filepath,
            'message': f'GIF succesvol opgeslagen: {filepath}'
        })
        
    except Exception as e:
        return jsonify({
            'error': f'Fout bij exporteren GIF: {str(e)}',
            'success': False
        }), 500
```

### 3. Extra CSS voor export dialog
```css
.export-dialog-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 9999;
}

.export-dialog {
    background: white;
    border-radius: 12px;
    padding: 30px;
    max-width: 500px;
    width: 90%;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
}

.export-dialog h3 {
    margin: 0 0 20px 0;
    color: #2c3e50;
}

.export-path-input {
    width: 100%;
    padding: 10px;
    border: 2px solid #e0e0e0;
    border-radius: 6px;
    font-size: 14px;
    margin: 10px 0;
}

.export-hint {
    font-size: 12px;
    color: #666;
    margin: 10px 0 20px 0;
}

.dialog-buttons {
    display: flex;
    gap: 10px;
    justify-content: flex-end;
}

.btn-primary, .btn-secondary {
    padding: 10px 20px;
    border: none;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s ease;
}

.btn-primary {
    background: #3498db;
    color: white;
}

.btn-primary:hover {
    background: #2980b9;
}

.btn-secondary {
    background: #e0e0e0;
    color: #666;
}

.btn-secondary:hover {
    background: #d0d0d0;
}
```

## Acceptatiecriteria

1. **Button zichtbaarheid**: 'Create All' button wordt alleen getoond na succesvolle upload van Excel bestand
2. **Export dialog**: Gebruiker kan export locatie aanpassen (standaard: C:\temp)
3. **Progress feedback**: Tijdens export wordt voortgang getoond met huidige persoon
4. **Bestandsnaam formaat**: GIF bestanden worden opgeslagen als `[YYYYMMDD]_[Persoonsnaam].gif`
5. **Error handling**: Bij fouten wordt duidelijke foutmelding getoond
6. **Performance**: Export proces blokkeert UI niet
7. **Kwaliteit**: GIF bestanden hebben goede kwaliteit en leesbare tekst
8. **Cross-platform**: Werkt op Windows, Mac en Linux (met aanpasbare paden)

## Te maken/wijzigen bestanden

1. **templates/index.html** - Toevoegen batch export sectie
2. **static/css/style.css** - Styling voor nieuwe componenten
3. **static/js/main.js** - JavaScript logica voor batch export
4. **app.py** - Nieuwe `/export_gif` endpoint
5. **requirements.txt** - Toevoegen cairosvg en Pillow dependencies
6. **project_info.txt** - Update met nieuwe functionaliteit
7. **project_stappen.txt** - Markeer deze stap als voltooid

## Branch
Ontwikkel in branch: `feature/create-all-button`
