### ISSUE TITLE
Batch Export Functionaliteit - Exporteer alle personen met één klik

### ISSUE THREAD

**Issue by Fbeunder** [Fbeunder/RadarChart#27]
## Beschrijving
Implementeer een batch export functionaliteit waarmee gebruikers met één klik voor alle personen in de dataset een PNG bestand kunnen genereren en downloaden. Deze functie moet toegankelijk zijn via een nieuwe button in de interface.

## Doel en Nut
**Doel:** HR-professionals en managers in staat stellen om snel voor alle medewerkers feedbackrapporten te genereren zonder handmatig door elke persoon te moeten klikken.

**Doelgroep:** HR-professionals die feedback sessies voorbereiden voor meerdere medewerkers, teamleiders die teamoverzichten willen maken, en managers die rapporten nodig hebben voor beoordelingsgesprekken.

**Nut en Noodzaak:**
- **Tijdsbesparing:** In plaats van 20+ keer handmatig exporteren voor een team, één klik voor alles
- **Consistentie:** Alle exports hebben dezelfde datum/tijd en formatting
- **Volledigheid:** Geen risico dat iemand wordt overgeslagen
- **Professionaliteit:** Gestandaardiseerde naamgeving voor archivering en documentatie

### 1. Backend Aanpassingen (app.py)
Nieuwe route toevoegen:
```python
@app.route('/get_all_persons_data')
def get_all_persons_data():
    """Retourneer data voor alle personen voor batch export"""
    try:
        if not processed_data["persons"]:
            return jsonify({
                'error': 'Geen data beschikbaar',
                'success': False
            }), 404
        
        all_persons_data = []
        for person_name in processed_data["available_persons"]:
            person_data = processed_data["persons"][person_name]
            all_persons_data.append({
                'person_name': person_name,
                'scores': {
                    'individual_scores': person_data["scores"],
                    'team_averages': processed_data["team_averages"]
                }
            })
        
        return jsonify({
            'success': True,
            'persons_data': all_persons_data,
            'total_persons': len(all_persons_data)
        })
    except Exception as e:
        return jsonify({
            'error': f'Fout bij ophalen data: {str(e)}',
            'success': False
        }), 500
```

### 2. Frontend UI Aanpassingen (templates/index.html)
Voeg batch export controls toe na de bestaande export controls:
```html
<!-- Batch Export Controls -->
<div id="batchExportControls" class="batch-export-controls" style="display: none;">
    <h4>📦 Batch Export</h4>
    <p class="batch-info">Exporteer radar charts voor alle <span id="totalPersonsCount">0</span> personen in één keer</p>
    <button id="batchExportBtn" class="batch-export-btn">
        <span class="btn-icon">📥</span>
        Exporteer Alle Personen als PNG
    </button>
    <div id="batchExportProgress" class="batch-progress" style="display: none;">
        <div class="batch-progress-bar">
            <div class="batch-progress-fill"></div>
        </div>
        <div class="batch-progress-text">
            <span id="batchProgressCurrent">0</span> / <span id="batchProgressTotal">0</span> voltooid
        </div>
    </div>
    <div id="batchExportStatus" class="batch-status" style="display: none;"></div>
</div>
```

### 3. Styling Toevoegen (static/css/style.css)
```css
/* Batch Export Styles */
.batch-export-controls {
    background-color: #f8f9fa;
    border: 2px solid #e9ecef;
    border-radius: 8px;
    padding: 20px;
    margin-top: 20px;
    text-align: center;
}

.batch-export-controls h4 {
    color: #2c3e50;
    margin-bottom: 10px;
}

.batch-info {
    color: #6c757d;
    margin-bottom: 15px;
}

.batch-info span {
    font-weight: bold;
    color: #3498db;
}

.batch-export-btn {
    background-color: #9b59b6;
    color: white;
    border: none;
    padding: 12px 24px;
    font-size: 16px;
    border-radius: 5px;
    cursor: pointer;
    transition: all 0.3s ease;
    display: inline-flex;
    align-items: center;
    gap: 8px;
}

.batch-export-btn:hover {
    background-color: #8e44ad;
    transform: translateY(-2px);
    box-shadow: 0 4px 8px rgba(0,0,0,0.2);
}

.batch-export-btn:disabled {
    background-color: #bdc3c7;
    cursor: not-allowed;
    transform: none;
}

.batch-progress {
    margin-top: 20px;
}

.batch-progress-bar {
    width: 100%;
    height: 30px;
    background-color: #ecf0f1;
    border-radius: 15px;
    overflow: hidden;
    position: relative;
}

.batch-progress-fill {
    height: 100%;
    background: linear-gradient(90deg, #9b59b6 0%, #8e44ad 100%);
    width: 0%;
    transition: width 0.3s ease;
    position: relative;
}

.batch-progress-fill::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    background: linear-gradient(
        45deg,
        rgba(255,255,255,.2) 25%,
        transparent 25%,
        transparent 50%,
        rgba(255,255,255,.2) 50%,
        rgba(255,255,255,.2) 75%,
        transparent 75%,
        transparent
    );
    background-size: 50px 50px;
    animation: move 1s linear infinite;
}

@keyframes move {
    0% {
        background-position: 0 0;
    }
    100% {
        background-position: 50px 50px;
    }
}

.batch-progress-text {
    text-align: center;
    margin-top: 10px;
    font-size: 14px;
    color: #7f8c8d;
}

.batch-status {
    margin-top: 15px;
    padding: 10px;
    border-radius: 5px;
    font-size: 14px;
}

.batch-status.success {
    background-color: #d4edda;
    color: #155724;
    border: 1px solid #c3e6cb;
}

.batch-status.error {
    background-color: #f8d7da;
    color: #721c24;
    border: 1px solid #f5c6cb;
}

.batch-status.processing {
    background-color: #cce5ff;
    color: #004085;
    border: 1px solid #b8daff;
}
```

### 4. Batch Export JavaScript Module (static/js/batchExport.js)
Nieuw bestand aanmaken:
```javascript
// Batch Export Functionality for RadarChart
class BatchExporter {
    constructor() {
        this.isExporting = false;
        this.exportQueue = [];
        this.completedExports = [];
        this.failedExports = [];
        this.initializeEventListeners();
    }

    initializeEventListeners() {
        document.addEventListener('DOMContentLoaded', () => {
            const batchExportBtn = document.getElementById('batchExportBtn');
            if (batchExportBtn) {
                batchExportBtn.addEventListener('click', () => this.startBatchExport());
            }
        });
    }

    showBatchExportControls(personCount) {
        const batchControls = document.getElementById('batchExportControls');
        const totalPersonsSpan = document.getElementById('totalPersonsCount');
        
        if (batchControls && totalPersonsSpan) {
            totalPersonsSpan.textContent = personCount;
            batchControls.style.display = 'block';
        }
    }

    async startBatchExport() {
        if (this.isExporting) return;
        
        this.isExporting = true;
        this.completedExports = [];
        this.failedExports = [];
        
        const batchBtn = document.getElementById('batchExportBtn');
        batchBtn.disabled = true;
        
        this.showBatchStatus('processing', '📊 Voorbereiden van batch export...');
        this.showProgress(true);
        
        try {
            // Haal data voor alle personen op
            const response = await fetch('/get_all_persons_data');
            const data = await response.json();
            
            if (!data.success) {
                throw new Error(data.error || 'Kon personen data niet ophalen');
            }
            
            this.exportQueue = data.persons_data;
            const total = this.exportQueue.length;
            
            this.updateProgressBar(0, total);
            this.showBatchStatus('processing', `🚀 Exporteren van ${total} radar charts...`);
            
            // Genereer datum voor bestandsnamen
            const exportDate = new Date().toISOString().split('T')[0];
            
            // Process exports met delay om browser niet te overbelasten
            for (let i = 0; i < this.exportQueue.length; i++) {
                const personData = this.exportQueue[i];
                
                try {
                    await this.exportSinglePerson(personData, exportDate);
                    this.completedExports.push(personData.person_name);
                } catch (error) {
                    console.error(`Export failed for ${personData.person_name}:`, error);
                    this.failedExports.push({
                        name: personData.person_name,
                        error: error.message
                    });
                }
                
                this.updateProgressBar(i + 1, total);
                
                // Kleine delay tussen exports
                await this.delay(100);
            }
            
            this.showCompletionStatus();
            
        } catch (error) {
            this.showBatchStatus('error', `❌ Batch export mislukt: ${error.message}`);
        } finally {
            this.isExporting = false;
            batchBtn.disabled = false;
            setTimeout(() => this.hideProgress(), 3000);
        }
    }

    async exportSinglePerson(personData, exportDate) {
        // Render de radar chart voor deze persoon (invisible)
        const tempContainer = document.createElement('div');
        tempContainer.style.position = 'absolute';
        tempContainer.style.left = '-9999px';
        tempContainer.style.width = '1000px';
        tempContainer.style.height = '800px';
        document.body.appendChild(tempContainer);
        
        try {
            // Initialize radar chart met person data
            const chartOptions = {
                w: 600,
                h: 600,
                margin: { top: 100, right: 200, bottom: 100, left: 200 },
                levels: 5,
                maxValue: 5,
                labelFactor: 1.3,
                wrapWidth: 120,
                opacityArea: 0.35,
                dotRadius: 4,
                strokeWidth: 2,
                roundStrokes: false,
                color: d3.scaleOrdinal().domain([0, 1]).range(["#3498db", "#27ae60"])
            };
            
            // Render chart
            const chart = initializeRadarChart(tempContainer, personData.scores, personData.person_name, chartOptions);
            
            // Wacht tot chart volledig gerenderd is
            await this.delay(500);
            
            // Gebruik ChartExporter om PNG te maken
            const svgElement = tempContainer.querySelector('svg');
            if (!svgElement) throw new Error('Chart rendering failed');
            
            // Maak complete export SVG
            const exporter = new ChartExporter();
            exporter.setCurrentPersonName(personData.person_name);
            const completeSvg = await exporter.createCompleteExportSvg(svgElement);
            
            // Genereer bestandsnaam
            const cleanName = personData.person_name
                .toLowerCase()
                .replace(/[^a-z0-9]/g, '_')
                .replace(/_+/g, '_')
                .replace(/^_|_$/g, '');
            const filename = `${exportDate}_${cleanName}.png`;
            
            // Converteer naar PNG en download
            await exporter.convertSVGtoPNG(completeSvg, filename);
            
            // Cleanup
            if (chart && chart.destroy) chart.destroy();
            
        } finally {
            // Verwijder temp container
            document.body.removeChild(tempContainer);
        }
    }

    updateProgressBar(current, total) {
        const progressFill = document.querySelector('.batch-progress-fill');
        const currentSpan = document.getElementById('batchProgressCurrent');
        const totalSpan = document.getElementById('batchProgressTotal');
        
        if (progressFill) {
            const percentage = (current / total) * 100;
            progressFill.style.width = `${percentage}%`;
        }
        
        if (currentSpan) currentSpan.textContent = current;
        if (totalSpan) totalSpan.textContent = total;
    }

    showProgress(show) {
        const progressDiv = document.getElementById('batchExportProgress');
        if (progressDiv) {
            progressDiv.style.display = show ? 'block' : 'none';
        }
    }

    hideProgress() {
        this.showProgress(false);
    }

    showBatchStatus(type, message) {
        const statusDiv = document.getElementById('batchExportStatus');
        if (statusDiv) {
            statusDiv.textContent = message;
            statusDiv.className = `batch-status ${type}`;
            statusDiv.style.display = 'block';
        }
    }

    showCompletionStatus() {
        const total = this.exportQueue.length;
        const succeeded = this.completedExports.length;
        const failed = this.failedExports.length;
        
        if (failed === 0) {
            this.showBatchStatus('success', 
                `✅ Alle ${succeeded} radar charts succesvol geëxporteerd!`);
        } else {
            let message = `⚠️ Export voltooid: ${succeeded} geslaagd, ${failed} mislukt.`;
            if (failed > 0) {
                message += ` Mislukte exports: ${this.failedExports.map(f => f.name).join(', ')}`;
            }
            this.showBatchStatus('error', message);
        }
    }

    delay(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
}

// Initialize batch exporter
window.batchExporter = new BatchExporter();
```

### 5. Integratie in main.js
Update main.js om batch export te activeren na succesvolle upload:
```javascript
// In de uploadFile success handler, na populatePersonDropdown:
if (window.batchExporter) {
    window.batchExporter.showBatchExportControls(data.persons.length);
}
```

### 6. HTML Script Tag Toevoegen
In index.html, voeg script tag toe:
```html
<script src="{{ url_for('static', filename='js/batchExport.js') }}"></script>
```

## Acceptatiecriteria
1. ✅ Een "Exporteer Alle Personen als PNG" button verschijnt na succesvolle data upload
2. ✅ De button toont het aantal personen dat geëxporteerd zal worden
3. ✅ Bij klikken worden voor alle personen PNG bestanden gegenereerd
4. ✅ Bestandsnamen volgen het format: `[YYYY-MM-DD]_[persoon_naam].png`
5. ✅ Progress bar toont voortgang tijdens export (X van Y voltooid)
6. ✅ Duidelijke feedback bij voltooiing (aantal geslaagd/mislukt)
7. ✅ Browser wordt niet geblokkeerd tijdens batch export
8. ✅ Exports hebben professionele uitstraling met titel, datum en legenda
9. ✅ Foutafhandeling voor individuele exports die mislukken

## Te maken/wijzigen bestanden
1. **app.py** - Nieuwe route `/get_all_persons_data` toevoegen
2. **templates/index.html** - Batch export controls HTML toevoegen
3. **static/css/style.css** - Batch export styling toevoegen
4. **static/js/batchExport.js** - Nieuwe module voor batch export functionaliteit (NIEUW)
5. **static/js/main.js** - Integratie met batch exporter na upload

## Branch naam
`feature/batch-export-functionality`
